version: 2.1

orbs:
  docker: circleci/docker@2.10.0

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: Install QEMU for Multi-Arch Support
          command: docker run --privileged --rm tonistiigi/binfmt --install all

      - docker/install-docker-buildx

      - docker/login:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

      - run:
          name: Build and Push Docker Image (ARM64)
          command: |
            docker buildx create --name mybuilder --use
            
            docker buildx build \
              --platform linux/arm64 \
              -t yehonatancohen/parties247-auto:latest \
              --push .

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main